const fs = require('fs');
const path = require('path');

const baseDir = 'e:/WOMEN/women';
const docsDir = path.join(baseDir, 'docs');

if (!fs.existsSync(docsDir)) {
  fs.mkdirSync(docsDir, { recursive: true });
}

const gitignoreContent = `# Miscellaneous
*.class
*.log
*.pyc
*.swp
.DS_Store
.atom/
.buildlog/
.history
.svn/
migrate_working_dir/

# IntelliJ related
*.iml
*.ipr
*.iws
.idea/

# The .vscode folder contains launch configuration and tasks you configure in
# VS Code which you may wish to be included in version control, so this line
# is commented out by default.
#.vscode/

# Flutter/Dart/Pub related
**/doc/api/
**/ios/Flutter/.last_build_id
.dart_tool/
.flutter-plugins
.flutter-plugins-dependencies
.pub-cache/
.pub/
/build/
/coverage/

# Symbolication related
app.*.symbols

# Obfuscation related
app.*.map.json

# Android Studio will place build artifacts here
/android/app/debug
/android/app/profile
/android/app/release

# Keystore files
*.jks
*.keystore

# Google Services
google-services.json
GoogleService-Info.plist

# macOS
.DS_Store
`;
fs.writeFileSync(path.join(baseDir, '.gitignore'), gitignoreContent);

const docs = {
  "MARKET_ANALYSIS.md": `# Market Analysis\n\n## Overview\nWomen's safety has become one of the most critical priorities globally. Millions of women travel independently every day for education, work, and personal activities, often facing varying degrees of safety concerns.\nModern smartphones, equipped with GPS and reliable communication networks, make it possible to build intelligent safety systems that provide instant emergency assistance.\n\n## Market Opportunity\n- **Increasing Smartphone Adoption:** Higher penetration in emerging markets allows safety apps to reach vulnerable populations.\n- **Growing Awareness:** Increased social awareness surrounding women's safety is driving demand for proactive personal security solutions.\n- **Government & Institutional Safety Initiatives:** Partnerships with local authorities and educational institutions.\n- **Smart City Projects:** Integration with upcoming smart city frameworks for better emergency response.\n\n## Market Size\nThe global personal safety application market is expanding rapidly due to an increasing demand for reliable emergency response systems.\n**Target Users:**\n- Students and youth\n- Working professionals (especially night shift workers)\n- Solo travelers and tourists\n- Parents monitoring their children's safety\n- Senior citizens\n\n## Competitors\n- **bSafe:** Offers live streaming and fake calls.\n- **Noonlight:** Connects directly to emergency dispatchers.\n- **Life360:** Primarily focused on family location tracking.\n- **Citizen App:** Crowd-sourced safety alerts.\n- **Safetipin:** Focuses on safety audits of public spaces.\n\n## Competitive Advantage\nOur application focuses on speed, reliability, and privacy:\n- **One-Tap SOS:** Immediate action without navigating complex menus.\n- **Offline SMS:** Works even without internet connectivity using direct telephony.\n- **Fast User Interface:** Designed to be accessible during high-stress situations.\n- **Privacy First:** Location is only shared when the SOS is triggered, respecting user autonomy.\n`,
  "BUSINESS_MODEL.md": `# Business Model\n\n## Revenue Sources\n1. **Premium Subscription (B2C):**\n   - Advanced features like live tracking, cloud backup of recordings, and AI threat detection.\n2. **Enterprise Safety Plans (B2B):**\n   - Corporate packages for employers to provide safety apps to their female employees, especially those working late hours.\n3. **University Partnerships (B2B2C):**\n   - Campus-wide licenses for students, integrating with campus security.\n4. **In-App Purchases:**\n   - One-time purchases for specialized emergency hardware (e.g., Bluetooth SOS buttons).\n\n## Free Features (Core Safety)\n- Basic SOS trigger\n- Emergency calling (Police, Ambulance)\n- SMS alerts with static GPS sharing\n- Management of up to 3 trusted contacts\n\n## Premium Features (Paid Tier)\n- **Live Continuous Tracking:** Real-time updates during an emergency.\n- **Cloud Backup:** Automatic secure upload of audio/video recordings when SOS is triggered.\n- **AI Detection:** Voice-activated SOS (e.g., recognizing distress keywords).\n- **Unlimited Contacts:** Add unlimited emergency contacts.\n- **Smartwatch Integration:** Trigger SOS directly from a wearable device.\n`,
  "PROBLEM_STATEMENT.md": `# Problem Statement\n\nMany women face constant and severe safety concerns in their daily lives, particularly while:\n- Traveling alone, especially at night.\n- Working late shifts or irregular hours.\n- Living alone in new or unfamiliar cities.\n- Using public transportation or ride-sharing services.\n\n**The Core Issue:**\nTraditional emergency methods (like dialing an emergency number and explaining the location) often take too much time, require the user to speak clearly, and are noticeable to attackers. In panic situations, finding contacts or dialing numbers manually is inefficient and dangerous.\n\n**Our Mission:**\nOur application reduces response time to virtually zero by allowing users to alert authorities and loved ones with a single, discreet tap.\n`,
  "SOLUTION.md": `# Proposed Solution\n\nThe Women Safety App provides a comprehensive, immediate, and reliable response mechanism for users in distress.\n\n## Key Offerings\n- **One-Tap SOS:** Instantly notifies all trusted contacts with an urgent message and GPS location.\n- **Live GPS Sharing:** accurately pinpoints the user's location using the device's native GPS capabilities.\n- **Trusted Contacts Management:** Easily configure who gets notified in an emergency.\n- **Direct Emergency Calling:** One tap to call local police or emergency hotlines without opening the dialer.\n- **Offline SMS Alerts:** Utilizes standard SMS so that alerts are sent even if mobile data is unavailable.\n- **Push Notifications:** Alerts configured contacts who also have the app installed.\n\nThe solution is specifically designed to work quickly, reliably, and with absolute minimal user interaction when it matters most.\n`,
  "HOW_IT_WORKS.md": `# How It Works\n\n## Step 1: Installation & Setup\nThe user installs the application from the App Store or Google Play.\n\n## Step 2: Permissions\nTo function effectively, the user grants necessary permissions:\n- **Location:** To fetch accurate GPS coordinates.\n- **SMS:** To send offline alerts to contacts.\n- **Phone:** To make direct calls to emergency services.\n- **Notifications:** To receive alerts from others.\n\n## Step 3: Configuration\nThe user adds their trusted contacts (family, friends, or colleagues) to the emergency list.\n\n## Step 4: Emergency Trigger\nDuring an emergency, the user opens the app and presses the prominent SOS button (or uses a widget/hardware shortcut).\n\n## Step 5: Automated Response\nThe application immediately and concurrently:\n- Fetches the current exact GPS location.\n- Sends an emergency SMS with the location link to all trusted contacts.\n- Dials the primary emergency service number (e.g., Police).\n- Sends push notifications to contacts (if integrated).\n\n## Step 6: Assistance\nTrusted contacts receive the alert instantly, complete with:\n- The user's exact location.\n- The time of the incident.\n- A call to action to assist or contact authorities.\n`,
  "FEATURES.md": `# Core Features\n\n## 🚨 One-Tap SOS\nInstantly send your current location and a distress message to your trusted contacts with a single button press.\n\n## 📍 Accurate GPS Tracking\nUtilizes advanced geolocator services to pinpoint your exact coordinates for faster response.\n\n## 📞 Direct Police Calling\nSkip the dialer. Tap the emergency call button to directly connect with local authorities.\n\n## 👥 Trusted Contacts\nEasily add, manage, and edit your network of trusted contacts from your phonebook.\n\n## 📶 Offline Functionality\nDoes not rely solely on internet connectivity; SOS alerts are sent via direct SMS.\n\n## 📱 Simple & Discreet UI\nA clutter-free interface designed specifically for high-stress situations.\n`,
  "WOMEN_EMPOWERMENT.md": `# Women Empowerment\n\n## Why This App Matters\n**Safety creates confidence.**\nWhen women feel safe and secure in their environment, they are empowered to:\n- Study freely without curfew concerns.\n- Travel independently and explore the world.\n- Work late shifts and pursue ambitious careers.\n- Participate fully in public and social life without fear.\n\n## Social Impact\nThis application supports women globally by:\n- **Reducing Response Time:** Bridging the gap between an emergency and the arrival of help.\n- **Increasing Confidence:** Acting as a digital safety net.\n- **Providing Quick Communication:** Ensuring loved ones are always informed.\n- **Fostering Independence:** Helping women make choices based on ambition, not fear.\n\n## Sustainable Development Goals (SDGs)\nThis project directly aligns with several UN SDGs:\n- **Goal 5: Gender Equality** (Empowering women through safety).\n- **Goal 3: Good Health and Well-being** (Reducing violence and trauma).\n- **Goal 11: Sustainable Cities and Communities** (Making public spaces safer).\n- **Goal 9: Industry, Innovation, and Infrastructure** (Using technology for social good).\n`,
  "TARGET_AUDIENCE.md": `# Target Audience\n\nOur primary users encompass a wide demographic of individuals who prioritize personal safety.\n\n## 👩‍💼 Working Professionals\nWomen commuting to and from work, especially those working night shifts, in retail, healthcare, or corporate sectors.\n\n## 🎓 Students\nCollege and university students traveling across campuses, libraries, and dormitories, often late at night.\n\n## 🌍 Solo Travelers\nTourists and digital nomads exploring new cities and unfamiliar environments independently.\n\n## 👨‍👩‍👧 Parents & Families\nParents who wish to ensure the safety of their daughters (and sons) when they are away from home.\n\n## 👵 Senior Citizens\nElderly individuals who may need urgent medical or physical assistance and require an easy-to-use SOS tool.\n`,
  "FUTURE_SCOPE.md": `# Future Scope\n\nWe are continuously working to make the platform smarter and more resilient. Future updates will include:\n\n- **AI Threat Detection:** Voice recognition to trigger SOS based on distress keywords or screams.\n- **Fake Call Feature:** Allowing users to trigger a simulated incoming phone call to gracefully exit uncomfortable situations.\n- **Wearable Support & Smartwatch SOS:** Trigger the SOS directly from an Apple Watch, Wear OS device, or Bluetooth button without taking out the phone.\n- **Live Video/Audio Recording:** Automatically start recording media when SOS is triggered and sync it securely to the cloud.\n- **Community Alerts (Crowdsourcing Help):** Notify nearby app users when an SOS is triggered so community members can offer immediate assistance.\n- **Police API Integration:** Direct integration with local emergency dispatch APIs for automated dispatching.\n- **AI Chat Assistant:** A companion bot to guide users on safety practices and legal rights.\n`,
  "TECH_STACK.md": `# Technology Stack\n\n## 💻 Frontend\n- **Framework:** Flutter (Cross-platform for iOS and Android)\n- **Language:** Dart\n\n## ⚙️ Backend & Cloud Services\n- **Platform:** Firebase\n- **Services:** Firebase Authentication, Cloud Firestore, Firebase Cloud Messaging (FCM)\n\n## 📦 Core Packages\n- \`geolocator\`: For highly accurate GPS location fetching.\n- \`telephony\` / \`flutter_sms\`: For sending background SMS.\n- \`url_launcher\` & \`flutter_phone_direct_caller\`: For initiating phone calls.\n- \`shared_preferences\`: For local storage of settings and contacts.\n- \`provider\`: For robust state management.\n- \`permission_handler\`: For managing OS-level permissions dynamically.\n\n## 🛠️ Development Tools\n- **IDE:** Android Studio, VS Code\n- **Version Control:** Git & GitHub\n- **CI/CD:** GitHub Actions (Planned)\n`,
  "SECURITY.md": `# Security & Privacy\n\nSecurity is a primary goal. The application is built with a privacy-first mindset to ensure user data is never compromised.\n\n## 🔐 Key Security Features\n- **Secure Authentication:** Robust login using Firebase Authentication.\n- **Encrypted Data:** User details and contact information are encrypted in transit and at rest.\n- **Permission-Based Access:** The app explicitly requests permissions (Location, SMS, Phone) and only uses them when absolutely necessary (e.g., during an SOS).\n- **No Background Tracking:** Location is NOT tracked in the background during normal operation. It is only fetched when the user explicitly triggers the SOS.\n- **Protected User Information:** Strict data access rules in Firebase prevent unauthorized read/write operations.\n`,
  "PRIVACY_POLICY.md": `# Privacy Policy\n\n**Last Updated:** [Date]\n\n## Data Collection\nWe only collect the minimum amount of data required to provide emergency assistance:\n- **Location Data:** Collected ONLY when the SOS button is triggered.\n- **Contacts:** Accessed locally to allow you to select your emergency contacts. This data is not uploaded to our servers unless explicitly backed up by the user.\n\n## Data Usage\n- Your location and emergency message are sent directly to your chosen contacts via SMS or Push Notifications.\n- We do not sell, rent, or share your personal data with third-party marketers.\n\n## Permissions\nThe app requires the following permissions to function:\n- **Location:** Essential for SOS features.\n- **SMS & Call:** Essential for notifying contacts and authorities offline.\n- **Contacts:** Essential for selecting who to notify.\n\n## User Rights\nYou have the right to request deletion of your account and all associated data at any time through the app settings.\n`,
  "USER_FLOW.md": `# User Flow\n\n## 1. Onboarding\n- **Splash Screen** -> **Welcome/Intro Sliders**\n- **Login/Registration** (Phone Number or Email/Google)\n- **Permissions Request:** Explicitly asking for SMS, Call, Location, and Contacts.\n\n## 2. Setup\n- **Home Screen** -> Prompt to add Emergency Contacts.\n- **Contact Selection:** Pick from the phonebook.\n\n## 3. Normal Operation\n- User opens the app.\n- Home screen displays a massive **SOS Button**.\n- Quick access buttons for Police, Ambulance, and Fire.\n\n## 4. Emergency State (SOS Triggered)\n- User taps the SOS button.\n- App fetches Location.\n- App sends SMS to contacts in the background.\n- App shows a countdown (optional 3 seconds to cancel).\n- App initiates a call to the default emergency number.\n`,
  "SYSTEM_ARCHITECTURE.md": `# System Architecture\n\n## High-Level Architecture\n1. **Client Layer (Mobile App):** \n   - Built with Flutter. Handles UI, State (Provider), and native API interactions (GPS, SMS, Calling).\n2. **Service Layer:**\n   - Background services to handle location fetching and SMS dispatching independently of the UI thread.\n3. **Backend Layer (Firebase):**\n   - **Authentication:** Manages user identity.\n   - **Firestore Database:** Stores user profiles and synced trusted contacts.\n   - **Cloud Messaging:** Handles push notifications between users.\n\n## Data Flow (SOS Event)\n1. User triggers SOS -> Mobile Client requests Location.\n2. OS Location Services return Lat/Lng.\n3. Mobile Client formats an Emergency Message with Google Maps link.\n4. Mobile Client invokes Native SMS API to dispatch messages locally.\n5. Mobile Client concurrently sends an API request to Firebase to trigger Push Notifications.\n6. Mobile Client invokes Native Dialer API to call Authorities.\n`,
  "ROADMAP.md": `# Product Roadmap\n\n## 🎯 Phase 1: Core Functionality (Version 1.0)\n- User Authentication.\n- SOS Button functionality.\n- GPS Location fetching.\n- Offline SMS Dispatch.\n- Emergency Contacts Management.\n\n## 🚀 Phase 2: Cloud Integration (Version 2.0)\n- Firebase Database synchronization for contacts.\n- Push Notifications for real-time alerts.\n- UI/UX improvements and animations.\n\n## 🧠 Phase 3: Advanced Features (Version 3.0)\n- Live Location Tracking (Continuous updates).\n- Fake Call Simulation.\n- Voice-activated SOS Commands.\n- Smartwatch / Wear OS Integration.\n\n## 🌐 Phase 4: Expansion (Version 4.0)\n- Community Alerts (Crowdsourced Safety).\n- Direct Police API Integration (where supported).\n- Machine Learning based Safety Prediction (safe routing).\n`,
  "FAQ.md": `# Frequently Asked Questions (FAQ)\n\n## Does the app work offline?\n**Yes.** The core SOS feature relies on your cellular network to send standard SMS messages. As long as you have a cell signal, the app can send alerts even without active mobile data.\n\n## Is GPS required?\n**Yes.** For your contacts to know where to find you, GPS must be enabled. If GPS is off, the app will prompt you to turn it on, and will attempt to send the last known location or just a generic distress message if location is completely unavailable.\n\n## Can I add multiple contacts?\n**Yes.** You can add multiple trusted contacts from your phonebook. We recommend adding at least 3 close friends or family members.\n\n## Is my data secure?\n**Yes.** Your data is stored securely. Your location is never tracked in the background and is only calculated and shared at the exact moment you press the SOS button.\n\n## Is the app free?\n**Yes.** All core safety features (SOS, Location, SMS, Calling) are completely free and will always remain free.\n`,
  "CONTRIBUTING.md": `# Contributing to Women Safety App\n\nWe love your input! We want to make contributing to this project as easy and transparent as possible.\n\n## How to Contribute\n1. **Fork the Repository:** Fork the project to your own GitHub account.\n2. **Clone:** Clone it to your local machine.\n3. **Branch:** Create a new branch for your feature or bug fix.\n   \`\`\`bash\n   git checkout -b feature/your-feature-name\n   \`\`\`\n4. **Develop:** Make your changes, ensuring you follow the existing code style and structure.\n5. **Test:** Run the app and ensure all features work perfectly.\n6. **Commit:** Commit your changes with clear, descriptive commit messages.\n7. **Push:** Push to your fork and submit a Pull Request.\n\n## Coding Guidelines\n- Follow standard Dart and Flutter linting rules.\n- Ensure all UI is responsive and accessible.\n- Document any new complex logic or services.\n\n## Reporting Bugs\nIf you find a bug, please create an issue in the GitHub repository detailing the steps to reproduce it, the expected behavior, and your device specifications.\n`
};

for (const [filename, content] of Object.entries(docs)) {
  fs.writeFileSync(path.join(docsDir, filename), content);
}
console.log('Done!');
